### ISSUE TITLE
Can't manage the plug-in at all

### ISSUE THREAD

**Issue by migash** [1n3JgKl9pQ6cUMrW/acf-cleaner#1]
I can never even get to the admin screen.

![screen shot 2017-04-04 at 10 57 20 am](https://cloud.githubusercontent.com/assets/26146794/24663355/acd3bd40-1925-11e7-91c0-f2ee9ea99fdd.png)

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
That's a weird message, it is not triggered by the plugin itself (I did not code that message inside the plugin).

So I guess it's a message fired by WordPress itself.

Can it be a conflict with another plugin?

And is the file `admin.php` available in the plugin directory?

![image](https://cloud.githubusercontent.com/assets/15701574/24703106/0c001ff2-1a02-11e7-8ce1-4ee1d727292a.png)

**Comment by migash** [comment]
I figured out the glitch.

Your zip download is called "acf-cleaner-master.zip” so when installed in creates a plug-in called "acf-cleaner-master” which upon activation, and attempted use throws that error. If I then deactivate and change the name on the server to "acf-cleaner” and reactivate  … still no joy. 

Seems the only way to make it work is to rename the folder “acf-cleaner” prior to uploading and activating. At least that was my experience.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
The `...-master` folder is created by Git(Hub) when you download the package.

I'll update the `README.md` file for proper use of the zip-package. Thanks.

**Comment by Hube2** [comment]
You can solve this by changing 
```
define('ACF_CLEANER_PAGE', 'acf-cleaner/acf-cleaner-admin.php');
```
to
```
define('ACF_CLEANER_PAGE', plugin_dir_url(__FILE__ ).'acf-cleaner-admin.php');
```
or something similar so that the plugin folder name is not hard coded.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Thank you for the suggestion, but in this usercase it doesn't work.

It returns something like this;

```https://SITENAME/wp-content/plugins/acf-cleaner/acf-cleaner-admin.php```

Where it should create an URL like this;

```https://SITENAME/wp-admin/tools.php?page=acf-cleaner%2Facf-cleaner-admin.php```

The management-page is nested in the tools-section, so the syntax of the URL is different.

But I will try to figure it out!

**Comment by Hube2** [comment]
K, I see, you are using add_management_page(). I think this will work, but I'm not sure.
```
define('ACF_CLEANER_PAGE', plugin_basename(dirname(__FILE__) .'/acf-cleaner-admin.php'));
```
Sorry, I just saw the comments over on the ACF forum. The folder name with -master added is a common issue when getting plugins from github. There should be an option to DL without adding the version to the folder, if there is I haven't found it.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
The ```basename``` does the job - I've already pushed a new version. Thanks!

Ideally I would publish the plug-in straight from the WordPress plug-in page, preventing this issue, but I decided not to - because the plug-in is not meant for all users (but only for those willing to experiment and troubleshoot with both ACF and the WordPress back-end).

**Comment by Hube2** [comment]
I have several plugins here for similar reasons. Some plugins are just not meant for the average user of the WP repo to install.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> I have several plugins here for similar reasons. Some plugins are just not meant for the average user of the WP repo to install.

To be honest this plug-in was never ment (mend?) for the public domain :)

But I found it useful and decided to publish it, for those who like fiddling around!
