### ISSUE TITLE
Issue on activation

### ISSUE THREAD

**Issue by magicstickuk** [1n3JgKl9pQ6cUMrW/acf-cleaner#2]
Hey mate. Thanks for the plugin. Wanted to give it a try but when i go to Tools > ACF Cleaner it takes me to this url:

/wp-admin/acf-cleaner/admin.php

Which is a 404 for me :-(

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
That's strange - the URL should be;

{site} /wp-admin/tools.php?page=acf-cleaner%2Fadmin.php

 ...or...

{site} /wp-admin/admin.php?page=acf-cleaner%2Fadmin.php

Did you click on the link from the plugins-page, or the entry in the sidebar (stored under "tools").

**Comment by magicstickuk** [comment]
As I said it was under the tools >Acf cleaner on the sidebar :-(

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
I will push an update within minutes, may be that will help.

In the meantime, does this URL work for you?

{your_site_root} /wp-admin/tools.php?page=acf-cleaner%2Fadmin.php

**Comment by friendofdog** [comment]
I'm having the same issue. Even by going to {your_site_root} /wp-admin/tools.php?page=acf-cleaner%2Fadmin.php I get the error...

Sorry, you are not allowed to access this page.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
I will investigate it once again.

I have implemented the plug-in on several sites, running on different servers - and they all work well, so I really can't tell what's the issue right now.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
It could have something to do with other plug-ins;

https://wordpress.org/support/topic/wp-admin-sorry-you-are-not-allowed-to-access-this-page/

Try de-activating them all, and activate only ACF Cleaner - when this works, try activating the others one by one.

Or it's a specific user-role issue, where admins do not have access to the plug-in (set by WordPress, not by this plug-in in particular).

https://wordpress.org/support/topic/wp-admin-sorry-you-are-not-allowed-to-access-this-page-1/page/2/

**Comment by friendofdog** [comment]
Pardon the late reply... It was a plugin conflict. I had made a plugin which interacts with WPML and ACF, it caused some communication issues between the two.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Glad to hear it worked for you.
