### ISSUE TITLE
Error: Table doesn't exist

### ISSUE THREAD

**Issue by felixdorner** [1n3JgKl9pQ6cUMrW/acf-cleaner#3]
Hey, I get this error:

Error : there was an error running the 1st query [Table 'local.wp_posts' doesn't exist].
Error : there was an error running the 4th query [Table 'local.wp_postmeta' doesn't exist].

This issue might occur because my tables are prefixed differently than 'wp'.

Any idea how to solve this?

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> Any idea how to solve this?

I can build an option for different 'prefixes'.

I will check it out this weekend, thx!

**Comment by felixdorner** [comment]
Sounds great! Until then I could adjust your code for my needs if you tell where to look? Like replacing 'wp_' with 'wp_myprefix_' in one or two places?

Cheers

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
You can try to change this file;

'acf-cleaner-queries.php'

Line #094 : wp_posts
Line #140 : wp_postmeta
Line #188 : wp_postmeta
Line #248 : wp_postmeta
Line #284 : wp_postmeta
Line #366 : wp_postmeta

Please, backup you database before doing any queries... and don't forget;

For the best result, the ACF-field must have an unique prefix as well
(defaults to 'ACF__' but that one you can change already on the
plugin-page itself).

**Comment by felixdorner** [comment]
Cool thanks!

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
New version now supports custom pre-fixes for the WP-tables.
