### ISSUE TITLE
Errors on acf-cleaner-queries

### ISSUE THREAD

**Issue by littlehawk** [1n3JgKl9pQ6cUMrW/acf-cleaner#5]
Hi!
After the plugins installation and activation, in ACF Cleaner Manage page I found this errors:
`Notice: Undefined variable: array_fields in xxx/public_html/wp-content/plugins/acf-cleaner/acf-cleaner-queries.php on line 132
Notice: Undefined variable: array_fields in xxx/public_html/wp-content/plugins/acf-cleaner/acf-cleaner-queries.php on line 140
Warning: array_map(): Argument #2 should be an array in xxx/public_html/wp-content/plugins/acf-cleaner/acf-cleaner-queries.php on line 140
Warning: implode(): Invalid arguments passed in xxx/public_html/wp-content/plugins/acf-cleaner/acf-cleaner-queries.php on line 140
Notice: Undefined variable: array_fields in xxx/public_html/wp-content/plugins/acf-cleaner/acf-cleaner-queries.php on line 143
Notice: Undefined variable: array_fields in xxx/public_html/wp-content/plugins/acf-cleaner/acf-cleaner-queries.php on line 188
Warning: implode(): Invalid arguments passed in xxx/public_html/wp-content/plugins/acf-cleaner/acf-cleaner-queries.php on line 188
Notice: Undefined variable: array_fields in xxx/public_html/wp-content/plugins/acf-cleaner/acf-cleaner-queries.php on line 191`

To solve theme, simply move the line 105 to line 93. ;-)

Regards.

P.S.: Your plugin is awesome. Thanks!

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
That's weird - I've never seen that error-message.

Which PHP version are you running?

I'll investigate the issue this weekend.

BTW. you domainname is included in the error-report; be careful with it :)

**Comment by littlehawk** [comment]
PHP version is 7.0.10.
After my personal investigation, I found that the problem is caused by the non-initialization of the variable **array_fields**.
To solve the problem, just move line 105 to line 93.

BTW. Thanks! I have modified previous post ;-)

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Ah - my bad :) I did read "**remove** lines 105 to lines 93" (which of course, I won't do). :)

I'll swap the lines this weekend and apply the fix - thanks!
