### ISSUE TITLE
ACF_ prefix

### ISSUE THREAD

**Issue by TylerBarnes** [1n3JgKl9pQ6cUMrW/acf-cleaner#6]
Is adding the ACF_ prefix something that's done manually during development or something that acf does?

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Unfortunately, you have to prefix the entries by hand.

I wasn't able to find a quick and clean way to fetch all the ACF-fields at once (from the WordPress main database), so I ended up with this solution.

When starting a new site / project, it's always a good idea to have a solid syntax for your ACF-fields (it makes development a lot easier when you know how an ACF-field is named) - so when starting from scratch, it's not a big deal.

But the plug-in is not suitable for sites / projects that have their ACF-fields already named with a non-consequent syntax / name-prefix.

Sorry for that.
