### ISSUE TITLE
Still supported + improvements

### ISSUE THREAD

**Issue by wpsumo** [1n3JgKl9pQ6cUMrW/acf-cleaner#8]
@1n3JgKl9pQ6cUMrW Is the plugin still maintained?

I see the plugin is not able to clean all ACF fields that are orphan. Just tested and deleted a field group and it does not find them. Was used on an ACF options page. Now orphan but the plugin do not detect them. Do you still support the plugin and options pages?

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Unfortunately I am not in active WordPress development since a year or three.

So I am not using / maintaining this plug-in myself.

Please feel free to fork.

👍
